export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const FETCH_INGREDIENTS_REQUEST = "FETCH_INGREDIENTS_REQUEST";
export const FETCH_INGREDIENTS_SUCCESS = "FETCH_INGREDIENTS_SUCCESS";
export const FETCH_INGREDIENTS_FAILURE = "FETCH_INGREDIENTS_FAILURE";

export const orderActionTypes = {
	PURCHASE_INIT: "PURCHASE_INIT",
	PURCHASE_BURGER_REQUEST: "PURCHASE_BURGER_REQUEST",
	PURCHASE_BURGER_SUCCESS: "PURCHASE_BURGER_SUCCESS",
	PURCHASE_BURGER_FAILURE: "PURCHASE_BURGER_FAILURE",
	FETCH_ORDER_REQUEST: "FETCH_ORDER_REQUEST",
	FETCH_ORDER_SUCCESS: "FETCH_ORDER_SUCCESS",
	FETCH_ORDER_FAILURE: "FETCH_ORDER_FAILURE",
};

export const authActionTypes = {
	AUTH_REQUEST: "AUTH_REQUEST",
	AUTH_SUCCESS: "AUTH_SUCCESS",
	AUTH_FAILURE: "AUTH_FAILURE",
	AUTH_SIGNOUT: "AUTH_SIGNOUT",
	SET_AUTH_REDIRECT_PATH: "SET_AUTH_REDIRECT_PATH",
};
